site_name: Golang服务端入门与进阶指南
theme: readthedocs

nav: 
  - Go踩坑:
    - Go踩坑: Go踩坑.md
  - 个人实践总结:
    - 01 个人博客总结: 基础/个人实践.md
  - Golang基础总结:
    - 01 基础知识到循环: 基础/1.md
    - 02 容器类型: 基础/2.md
    - 03 函数闭包指针: 基础/3.md
    - 04 值/引用类型与异常处理: 基础/4.md
    - 05 结构体接口与反射: 基础/5.md
    - 06 各种内置模块的使用: 基础/6.md
    - 07 网编并发: 基础/7.md
  - 《Go语言圣经》笔记:
    - 00 写在最前: go圣经/0写在最前.md
    - 01 goroutine与channel: go圣经/1goroutine与channel.md
    - 02 基于共享变量的并发: go圣经/2基于共享变量的并发.md
    - 基础: go圣经/基础.md