site_name: Golang服务端入门与进阶指南
theme: readthedocs

nav: 
  - 个人实践总结:
    - 01 个人博客总结: 基础/个人实践.md
  - Golang基础总结:
    - 01 基础知识到循环: 基础/1.md
    - 02 容器类型: 基础/2.md
    - 03 函数闭包指针: 基础/3.md
    - 04 值/引用类型与异常处理: 基础/4.md
    - 05 结构体接口与反射: 基础/5.md
    - 06 各种内置模块的使用: 基础/6.md
    - 07 网编并发: 基础/7.md
  - The Go Programming Language:
    - 01 入门: go圣经/入门.md